In [31]:
import numpy as np
import pandas as pd

scores = pd.DataFrame(np.random.randint(50,101,size=(50,5)),
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
scores

    國文  英文   數學   地理   歷史
1   88  79   54   53   73
2   66  94   52   72   81
3   59  85   83   96   62
4   92  77   57   72   60
5   68  96   62   84   66
6   59  71   69   94   52
7   66  93   75   53   85
8   86  87   52   76   95
9   92  89   53   96   94
10  87  81   65   98   63
11  71  83   81   80   74
12  78  95   67   56   90
13  87  76   88   51   70
14  50  78   90   53   95
15  94  80   80   61   75
16  62  68   93   61   94
17  91  96   76   68   93
18  59  83   73   90   89
19  53  94   51   84   92
20  77  66   91  100   64
21  77  83   85   69   68
22  91  94   71   60   87
23  73  86   71   93   52
24  63  97   57   83   73
25  76  74   83   92   52
26  77  62   94   72   54
27  88  76   82   77   82
28  74  71   63   90   94
29  66  87   59   59  100
30  83  89   88   79   97
31  83  62   61   53   86
32  59  68   88   76   79
33  51  58   58   56   65
34  67  68   86   90   63
35  69  95  100   85   89
36  80  83   98   68   57
37  93  89   84   53   97
38  73  85   87   78   59
39  64  66   69   96   96
40  89  97   78   80   59
41  60  84   59   80   83
42  84  82   75   86   85
43  74  84   91   67   66
44  77  98   70   99   74
45  54  81   74   77   68
46  77  90   72   79   56
47  53  65   79   91   78
48  85  74   74   75   72
49  68  53   63   92   72
50  60  95   87   71   75

In [32]:
def abc(s):
    return s.max()
scores.apply(abc)

國文     94
英文     98
數學    100
地理    100
歷史    100
dtype: int64

In [33]:
def abc(s):
    return pd.Series([s.min(),s.max(),s.mean()],index=['最低分','最高分','平均'])
scores.apply(abc)

        國文     英文      數學      地理     歷史
最低分  50.00  53.00   51.00   51.00   52.0
最高分  94.00  98.00  100.00  100.00  100.0
平均   73.46  81.34   74.36   76.48   76.1

In [34]:
scores.index = scores.index.map(lambda i:f'{i}號')
scores

     國文  英文   數學   地理   歷史
1號   88  79   54   53   73
2號   66  94   52   72   81
3號   59  85   83   96   62
4號   92  77   57   72   60
5號   68  96   62   84   66
6號   59  71   69   94   52
7號   66  93   75   53   85
8號   86  87   52   76   95
9號   92  89   53   96   94
10號  87  81   65   98   63
11號  71  83   81   80   74
12號  78  95   67   56   90
13號  87  76   88   51   70
14號  50  78   90   53   95
15號  94  80   80   61   75
16號  62  68   93   61   94
17號  91  96   76   68   93
18號  59  83   73   90   89
19號  53  94   51   84   92
20號  77  66   91  100   64
21號  77  83   85   69   68
22號  91  94   71   60   87
23號  73  86   71   93   52
24號  63  97   57   83   73
25號  76  74   83   92   52
26號  77  62   94   72   54
27號  88  76   82   77   82
28號  74  71   63   90   94
29號  66  87   59   59  100
30號  83  89   88   79   97
31號  83  62   61   53   86
32號  59  68   88   76   79
33號  51  58   58   56   65
34號  67  68   86   90   63
35號  69  95  100   85   89
36號  80  83   98   68   57
37號  93  89   84   53   97
38號  73  85   87   78   59
39號  64  66   69   96   96
40號  89  97   78   80   59
41號  60  84   59   80   83
42號  84  82   75   86   85
43號  74  84   91   67   66
44號  77  98   70   99   74
45號  54  81   74   77   68
46號  77  90   72   79   56
47號  53  65   79   91   78
48號  85  74   74   75   72
49號  68  53   63   92   72
50號  60  95   87   71   75

In [35]:
def abc1(item):
    return pd.Series([item.sum(),item.mean()],index=['總分','平均'])
scores.apply(abc1,axis=1)

        總分    平均
1號   347.0  69.4
2號   365.0  73.0
3號   385.0  77.0
4號   358.0  71.6
5號   376.0  75.2
6號   345.0  69.0
7號   372.0  74.4
8號   396.0  79.2
9號   424.0  84.8
10號  394.0  78.8
11號  389.0  77.8
12號  386.0  77.2
13號  372.0  74.4
14號  366.0  73.2
15號  390.0  78.0
16號  378.0  75.6
17號  424.0  84.8
18號  394.0  78.8
19號  374.0  74.8
20號  398.0  79.6
21號  382.0  76.4
22號  403.0  80.6
23號  375.0  75.0
24號  373.0  74.6
25號  377.0  75.4
26號  359.0  71.8
27號  405.0  81.0
28號  392.0  78.4
29號  371.0  74.2
30號  436.0  87.2
31號  345.0  69.0
32號  370.0  74.0
33號  288.0  57.6
34號  374.0  74.8
35號  438.0  87.6
36號  386.0  77.2
37號  416.0  83.2
38號  382.0  76.4
39號  391.0  78.2
40號  403.0  80.6
41號  366.0  73.2
42號  412.0  82.4
43號  382.0  76.4
44號  418.0  83.6
45號  354.0  70.8
46號  374.0  74.8
47號  366.0  73.2
48號  380.0  76.0
49號  348.0  69.6
50號  388.0  77.6

In [36]:
one_student = scores.iloc[0]
less_student = one_student[one_student < 60]
less_student

數學    54
地理    53
Name: 1號, dtype: int64

In [37]:
less_student.count()
",".join(less_student.index.values.tolist())

'數學,地理'

In [38]:
def abc1(item):
    less_student = item[item < 60]
    less_count = less_student.count()
    less_str = ",".join(less_student.index.values.tolist())
    
    return pd.Series([item.sum(),item.mean(),less_count,less_str],index=['總分','平均','不及格科目數','不及格科目'])
scores.apply(abc1,axis=1)

      總分    平均  不及格科目數        不及格科目
1號   347  69.4       2        數學,地理
2號   365  73.0       1           數學
3號   385  77.0       1           國文
4號   358  71.6       1           數學
5號   376  75.2       0
6號   345  69.0       2        國文,歷史
7號   372  74.4       1           地理
8號   396  79.2       1           數學
9號   424  84.8       1           數學
10號  394  78.8       0
11號  389  77.8       0
12號  386  77.2       1           地理
13號  372  74.4       1           地理
14號  366  73.2       2        國文,地理
15號  390  78.0       0
16號  378  75.6       0
17號  424  84.8       0
18號  394  78.8       1           國文
19號  374  74.8       2        國文,數學
20號  398  79.6       0
21號  382  76.4       0
22號  403  80.6       0
23號  375  75.0       1           歷史
24號  373  74.6       1           數學
25號  377  75.4       1           歷史
26號  359  71.8       1           歷史
27號  405  81.0       0
28號  392  78.4       0
29號  371  74.2       2        數學,地理
30號  436  87.2       0
31號  345  69.0       1           地理
32號  370  74.0       1           國文
33號  288  57.6       4  國文,英文,數學,地理
34號  374  74.8       0
35號  438  87.6       0
36號  386  77.2       1           歷史
37號  416  83.2       1           地理
38號  382  76.4       1           歷史
39號  391  78.2       0
40號  403  80.6       1           歷史
41號  366  73.2       1           數學
42號  412  82.4       0
43號  382  76.4       0
44號  418  83.6       0
45號  354  70.8       1           國文
46號  374  74.8       1           歷史
47號  366  73.2       1           國文
48號  380  76.0       0
49號  348  69.6       1           英文
50號  388  77.6       0